#!/usr/bin/env node

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Import the server rendering function (requires ts-node/esm at runtime)
import { render } from '../src/entry-server.ts';
import { blogPosts } from '../src/data/blogPosts.ts';
import { portfolioProjects } from '../src/data/portfolioProjects.ts';

const outDir = path.resolve(__dirname, '..', 'dist');

// Load the built index.html template (generated by Vite)
const templatePath = path.join(outDir, 'index.html');

async function prerender() {
  const template = await readFile(templatePath, 'utf8');
  const staticRoutes = [
    '/',
    '/lahore',
    '/seo-services',
    '/web-design',
    '/creative',
    '/marketing',
    '/portfolio',
    '/pricing',
    '/blog',
    '/contact'
  ];
  const dynamicRoutes = [];
  blogPosts.forEach(p => dynamicRoutes.push(`/blog/${p.slug}`));
  portfolioProjects.forEach(p => dynamicRoutes.push(`/portfolio/${p.slug}`));

  const allRoutes = staticRoutes.concat(dynamicRoutes);
  console.log('Starting prerender for', allRoutes.length, 'routes');
  for (const route of allRoutes) {
    const html = template.replace('<!--app-html-->', render(route));
    const outPath = route === '/'
      ? path.join(outDir, 'index.html')
      : path.join(outDir, route.replace(/^\//, ''), 'index.html');
    await mkdir(path.dirname(outPath), { recursive: true });
    await writeFile(outPath, html, 'utf8');
    console.log(`Rendered ${route} → ${outPath}`);
  }
}

prerender().catch(err => {
  console.error('Prerender failed:', err);
  process.exit(1);
});
